# SFT Training Configuration
model:
  name_or_path: "Qwen/Qwen3-0.6B"  
  use_lora: true
  lora_config:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.1
    target_modules:
      - "q_proj"
      - "k_proj"
      - "v_proj"
      - "o_proj"
      - "gate_proj"
      - "up_proj"
      - "down_proj"
    task_type: "CAUSAL_LM"
  load_in_8bit: false
  load_in_4bit: false  # Set to true for QLoRA

data:
  max_length: 2048
  train_batch_size: 4
  eval_batch_size: 8
  num_workers: 4

training:
  num_epochs: 3
  learning_rate: 2e-4
  warmup_ratio: 0.1
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  fp16: true
  optim: "paged_adamw_32bit"
  lr_scheduler_type: "cosine"
  save_strategy: "steps"
  save_steps: 100
  eval_strategy: "steps"
  eval_steps: 100
  logging_steps: 10
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  
  # Early stopping
  early_stopping_patience: 3
  early_stopping_threshold: 0.0001

wandb:
  project: "qwen-customer-support"
  name: "sft-training"
  tags: ["sft", "customer-support"]

output_dir: "experiments/{timestamp}/sft"